export class GameUI {
  constructor({ app, theme, documentRef = document, actions = {} } = {}) {
    if (!app) throw new Error('GameUI requires an app element');
    this.app = app; this.theme = theme; this.document = documentRef; this.actions = actions; this.elements = {}; this.timeouts = new Set(); this.build();
  }
  build() { this.app.replaceChildren(); this.buildBackground(); this.buildTable(); this.buildHUD(); this.buildRuleBanner(); this.buildGameZones(); this.buildOverlays(); }
  buildBackground() { const background = this.document.createElement('div'); background.className = 'library-bg'; this.elements.bg = background; this.theme.renderBackground(background); this.app.append(background); }
  buildTable() { this.elements.table = this.document.createElement('div'); this.elements.table.className = 'game-table'; this.app.append(this.elements.table); }
  buildHUD() { const hud = this.document.createElement('div'); hud.className = 'hud-bar'; const items = [['УРОВЕНЬ', 'hud-level', '1'], ['СЛОЖНОСТЬ', 'hud-diff', '1'], ['ХОДЫ', 'hud-moves', '0'], ['ОЧКИ', 'hud-score', '0']]; for (const [label, id, value] of items) { const item = this.document.createElement('div'); item.className = 'hud-item'; item.append(`${label} `); const valueElement = this.document.createElement('span'); valueElement.id = id; valueElement.textContent = value; item.append(valueElement); hud.append(item); } const undo = this.document.createElement('button'); undo.className = 'menu-button undo-button'; undo.type = 'button'; undo.append('↶ ', 'Назад'); undo.addEventListener('click', () => this.actions.onUndo?.()); hud.append(undo); const menu = this.document.createElement('button'); menu.className = 'menu-button'; menu.type = 'button'; menu.append('☰ ', 'Меню'); menu.addEventListener('click', () => this.actions.onPause?.()); hud.append(menu); this.elements.hud = hud; this.elements.hudLevel = hud.querySelector('#hud-level'); this.elements.hudDiff = hud.querySelector('#hud-diff'); this.elements.hudMoves = hud.querySelector('#hud-moves'); this.elements.hudScore = hud.querySelector('#hud-score'); this.app.append(hud); }
  buildRuleBanner() { const banner = this.document.createElement('div'); banner.className = 'rule-banner'; const title = this.document.createElement('h2'); title.id = 'rule-text'; const subtitle = this.document.createElement('div'); subtitle.className = 'sub'; subtitle.id = 'rule-sub'; banner.append(title, subtitle); this.elements.ruleBanner = banner; this.elements.ruleText = title; this.elements.ruleSub = subtitle; this.app.append(banner); }
  buildGameZones() { this.elements.comboDisplay = this.document.createElement('div'); this.elements.comboDisplay.className = 'combo-display'; this.elements.objectsZone = this.document.createElement('div'); this.elements.objectsZone.className = 'objects-zone'; this.elements.objectsZone.hidden = true; this.elements.containersZone = this.document.createElement('div'); this.elements.containersZone.className = 'containers-zone'; this.app.append(this.elements.comboDisplay, this.elements.objectsZone, this.elements.containersZone); }
  buildOverlays() { this.elements.failOverlay = this.createOverlay('fail-overlay', 'НЕТ ХОДОВ', 'Откати решение или начни уровень заново', [['retry', '↻ НАЧАТЬ ЗАНОВО', 'menu-btn-primary'], ['menu', '← В МЕНЮ', 'menu-btn-secondary']]); this.elements.pauseOverlay = this.createOverlay('pause-overlay', '⏸ ПАУЗА', 'Головоломка приостановлена', [['resume', '▶ ПРОДОЛЖИТЬ', 'menu-btn-primary'], ['settings', '⚙ НАСТРОЙКИ', 'menu-btn-secondary'], ['menu', '← В МЕНЮ', 'menu-btn-secondary']]); }
  createOverlay(id, title, text, buttons) { const overlay = this.document.createElement('div'); overlay.className = 'modal-overlay'; overlay.id = id; const card = this.document.createElement('div'); card.className = 'modal-card'; const heading = this.document.createElement('div'); heading.className = 'modal-title'; heading.textContent = title; const description = this.document.createElement('p'); description.textContent = text; card.append(heading, description); for (const [action, label, className] of buttons) { const button = this.document.createElement('button'); button.className = `menu-btn ${className}`; button.type = 'button'; button.dataset.action = action; button.textContent = label; button.addEventListener('click', () => { this.hideOverlay(overlay); this.actions[`on${action[0].toUpperCase()}${action.slice(1)}`]?.(); }); card.append(button); } overlay.append(card); this.app.append(overlay); return overlay; }
  hideOverlay(overlay) { overlay?.classList.remove('active'); }
  updateHUD(level, difficulty, score, moves = 0) { this.elements.hudLevel.textContent = String(level); this.elements.hudDiff.textContent = String(difficulty); this.elements.hudScore.textContent = String(score); this.elements.hudMoves.textContent = String(moves); }
  setMoves(moves) { this.elements.hudMoves.textContent = String(moves); }
  showTimer() {} updateTimer() {} hideTimer() {}
  setRule(text, sub) { this.elements.ruleText.textContent = text ?? ''; this.elements.ruleSub.textContent = sub ? `${sub} · Берём только верхнюю книгу` : 'Берём только верхнюю книгу'; }
  renderObjects() { this.elements.objectsZone.replaceChildren(); }
  renderContainers(containers, objects = []) { const byId = new Map(objects.map(object => [object.uid, object])); const fragment = this.document.createDocumentFragment(); for (const container of containers) { const element = this.document.createElement('div'); element.className = 'shelf-container'; if (container.type === 'empty') element.classList.add('empty-shelf'); element.dataset.id = container.id; element.dataset.capacity = String(container.capacity); const header = this.document.createElement('div'); header.className = 'shelf-header'; const label = this.document.createElement('div'); label.className = 'shelf-label'; label.textContent = container.type === 'empty' ? 'СВОБОДНАЯ ПОЛКА' : `ПОЛКА ${container.index + 1}`; const count = this.document.createElement('span'); count.className = 'shelf-count'; count.textContent = `${container.items.length}/${container.capacity}`; header.append(label, count); const items = this.document.createElement('div'); items.className = 'shelf-items'; for (const [index, uid] of container.items.entries()) { const object = byId.get(uid); if (object) { const book = this.theme.renderBook(object); book.classList.toggle('top-book', index === 0); items.append(book); } } element.append(header, items); fragment.append(element); } this.elements.containersZone.replaceChildren(fragment); }
  updateTopBookClasses() { for (const shelf of this.elements.containersZone?.querySelectorAll('.shelf-container') ?? []) { const books = shelf.querySelectorAll('.shelf-items > .book-item'); books.forEach((book, index) => book.classList.toggle('top-book', index === 0)); } }
  moveToContainer(bookElement, containerElement, level) { const target = level.containers.find(container => container.id === containerElement?.dataset.id); const object = level.objects.find(item => item.uid === bookElement?.dataset.uid); const source = object && level.containers.find(container => container.id === object.shelfId); if (!object || !source || !target) return null; source.items = source.items.filter(uid => uid !== object.uid); target.items.unshift(object.uid); object.shelfId = target.id; object.depth = 0; this.placeElement(bookElement, source, target); return { sourceId: source.id, targetId: target.id, objectId: object.uid }; }
  undoMove(move, level) { const object = level.objects.find(item => item.uid === move.objectId); const source = level.containers.find(container => container.id === move.sourceId); const target = level.containers.find(container => container.id === move.targetId); const bookElement = this.elements.containersZone.querySelector(`[data-uid="${move.objectId}"]`); if (!object || !source || !target || !bookElement) return false; target.items = target.items.filter(uid => uid !== object.uid); source.items.unshift(object.uid); object.shelfId = source.id; object.depth = 0; this.placeElement(bookElement, target, source); return true; }
  placeElement(bookElement, source, target) { const targetElement = this.elements.containersZone.querySelector(`[data-id="${target.id}"]`); const sourceElement = this.elements.containersZone.querySelector(`[data-id="${source.id}"]`); const targetItems = targetElement?.querySelector('.shelf-items'); if (targetItems) targetItems.prepend(bookElement); bookElement.classList.remove('correct', 'dragging'); targetElement?.querySelector('.shelf-count') && (targetElement.querySelector('.shelf-count').textContent = `${target.items.length}/${target.capacity}`); sourceElement?.querySelector('.shelf-count') && (sourceElement.querySelector('.shelf-count').textContent = `${source.items.length}/${source.capacity}`); targetElement?.classList.toggle('empty-shelf', target.items.length === 0); sourceElement?.classList.toggle('empty-shelf', source.items.length === 0); this.updateTopBookClasses(); }
  isSolved(level) { return level.containers.every(container => { if (container.items.length === 0) return true; if (container.items.length !== level.capacity) return false; const colors = container.items.map(uid => level.objects.find(object => object.uid === uid)?.color); return colors.every(color => color && color === colors[0]); }); }
  showFail() { this.elements.failOverlay.classList.add('active'); } hideFail() { this.hideOverlay(this.elements.failOverlay); } showPauseMenu() { this.elements.pauseOverlay.classList.add('active'); } hidePauseMenu() { this.hideOverlay(this.elements.pauseOverlay); } showCombo(combo) { this.elements.comboDisplay.textContent = `СЕРИЯ x${combo}`; this.elements.comboDisplay.classList.add('show'); } hideCombo() { this.elements.comboDisplay.classList.remove('show'); }
  showPopup(x, y, text) { const element = this.document.createElement('div'); element.className = 'score-popup'; element.textContent = text; element.style.left = `${x}px`; element.style.top = `${y}px`; this.app.append(element); const timeout = setTimeout(() => { this.timeouts.delete(timeout); element.remove(); }, 700); this.timeouts.add(timeout); }
  destroy() { for (const timeout of this.timeouts) clearTimeout(timeout); this.timeouts.clear(); this.elements = {}; this.app.replaceChildren(); }
}